//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int InvoiceNo { get; set; }
        public int SaleID { get; set; }
        public double GST { get; set; }
        public double Discount { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    }
}
