//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Count
    {
        public int CountID { get; set; }
        public int MedID { get; set; }
        public int CustomerID { get; set; }
        public int Count1 { get; set; }
        public int TotalPrice { get; set; }
    }
}
