//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PharmacyManagementEntities : DbContext
    {
        public PharmacyManagementEntities()
            : base("name=PharmacyManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Count> Counts { get; set; }
        public virtual DbSet<CustomerDetail> CustomerDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<StockDetail> StockDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int AddProduct(Nullable<int> medid, string medName, string compName, Nullable<double> price, Nullable<System.DateTime> expDate, Nullable<int> stock)
        {
            var medidParameter = medid.HasValue ?
                new ObjectParameter("Medid", medid) :
                new ObjectParameter("Medid", typeof(int));
    
            var medNameParameter = medName != null ?
                new ObjectParameter("MedName", medName) :
                new ObjectParameter("MedName", typeof(string));
    
            var compNameParameter = compName != null ?
                new ObjectParameter("CompName", compName) :
                new ObjectParameter("CompName", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            var expDateParameter = expDate.HasValue ?
                new ObjectParameter("ExpDate", expDate) :
                new ObjectParameter("ExpDate", typeof(System.DateTime));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("Stock", stock) :
                new ObjectParameter("Stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProduct", medidParameter, medNameParameter, compNameParameter, priceParameter, expDateParameter, stockParameter);
        }
    
        public virtual int AddUser(string empname, string address, string email, Nullable<int> phone, string gender, Nullable<int> age, string role, string username, string password)
        {
            var empnameParameter = empname != null ?
                new ObjectParameter("empname", empname) :
                new ObjectParameter("empname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", empnameParameter, addressParameter, emailParameter, phoneParameter, genderParameter, ageParameter, roleParameter, usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<DisplayStockDetails_Result> DisplayStockDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DisplayStockDetails_Result>("DisplayStockDetails");
        }
    
        public virtual ObjectResult<EmployeeDetailDisplay_Result> EmployeeDetailDisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeDetailDisplay_Result>("EmployeeDetailDisplay");
        }
    }
}
