//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> CountID { get; set; }
    
        public virtual Count Count { get; set; }
        public virtual CustomerDetail CustomerDetail { get; set; }
    }
}
